# Generated by Django 5.2.15 on 2026-07-04 18:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ModelMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("accuracy", models.FloatField(verbose_name="دقت کلی")),
                ("precision", models.FloatField(verbose_name="صحت")),
                ("recall", models.FloatField(verbose_name="حساسیت")),
                ("f1_score", models.FloatField(verbose_name="معیار F1")),
                (
                    "roc_auc",
                    models.FloatField(blank=True, null=True, verbose_name="ROC-AUC"),
                ),
                (
                    "confusion_matrix_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="metrics/",
                        verbose_name="تصویر ماتریس درهم\u200cریختگی",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین بروزرسانی"),
                ),
            ],
            options={
                "verbose_name": "معیار ارزیابی",
                "verbose_name_plural": "معیارهای ارزیابی",
            },
        ),
        migrations.CreateModel(
            name="PredictionRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "original_image",
                    models.ImageField(
                        upload_to="uploads/%Y/%m/%d/", verbose_name="تصویر اصلی"
                    ),
                ),
                (
                    "heatmap_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="results/%Y/%m/%d/",
                        verbose_name="نقشه حرارتی",
                    ),
                ),
                (
                    "bbox_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="results/%Y/%m/%d/",
                        verbose_name="تصویر با کادر تشخیص",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        choices=[("PNEUMONIA", "ذات\u200cالریه"), ("NORMAL", "سالم")],
                        max_length=20,
                        verbose_name="برچسب تشخیص",
                    ),
                ),
                ("confidence", models.FloatField(verbose_name="درصد اطمینان")),
                (
                    "processing_time",
                    models.IntegerField(
                        default=0, verbose_name="زمان پردازش (میلی\u200cثانیه)"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="تاریخ ایجاد"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="آدرس IP"
                    ),
                ),
            ],
            options={
                "verbose_name": "رکورد تشخیص",
                "verbose_name_plural": "رکوردهای تشخیص",
                "ordering": ["-created_at"],
            },
        ),
    ]
